name: PR Checks
run-name: PR Checks
on: [push]
jobs:
  Style-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner and is on branch ${{ github.ref }}."
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node -v
      - run: echo "üçè This job's status is ${{ job.status }}."
